"""add phone number

Revision ID: 41bf607eac84
Revises: 6645a3bfbdfb
Create Date: 2022-12-22 15:48:08.254442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bf607eac84'
down_revision = '6645a3bfbdfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
