"""add phone number

Revision ID: 6645a3bfbdfb
Revises: 914dee4341c9
Create Date: 2022-12-22 15:47:03.299377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6645a3bfbdfb'
down_revision = '914dee4341c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
